routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');
Route::resource('event', 'EventController')->only('show');
Route::resource('order', 'OrderController')->only('store');

Auth::routes();

Route::group(['namespace' => 'Admin', 'middleware' => 'auth'], function () {
    Route::get('admin', 'DashboardController@index')->name('admin');
    Route::resource('admin/pages', 'PageController')->only('index', 'edit', 'update')->names('admin.pages');
    Route::get('admin/orders', 'OrderController@index')->name('admin.orders');
    Route::get('admin/orders/{id}/delete', 'OrderController@destroy')->name('admin.orders.delete');
    Route::get('admin/events', 'EventController@index')->name('admin.events');
    Route::get('admin/users', 'UserController@index')->name('admin.users');
    Route::get('admin/roles', 'RoleController@index')->name('admin.roles');
});

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Contracts\Translation\Translator;
use Illuminate\Database\Eloquent\Model;
use App\Libraries\DateFormat;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Order extends Model
{
    protected $fillable = ['event_id', 'name', 'surname', 'phone', 'email', 'grade', 'ip', 'utm'];
    protected $perPage  = 2; // Сколько заявок выводить на 1 странице

    /**
     * Преобразуем дату создания в соответствии с правилами русского языка
     *
     * @param $attr
     *
     * @return array|Translator|string|null
     */
    public function getCreatedAtAttribute($attr)
    {
        return DateFormat::post($attr);
    }

    /**
     * Преобразуем дату обновления в соответствии с правилами русского языка
     *
     * @param $attr
     *
     * @return array|Translator|string|null
     */
    public function getUpdatedAtAttribute($attr)
    {
        return DateFormat::post($attr);
    }

    /**
     * Заявка может относиться только к одному мероприятию
     * Order::find(id)->event
     *
     * @return BelongsTo
     */
    public function event()
    {
        return $this->belongsTo(Event::class);
    }

    /**
     * Вывод всех заявок, отсортированных по последней дате, с пагинацией или без
     *
     * @param      $object
     * @param bool $pagination
     *
     * @return mixed
     */
    public function getSortedOrders($object, $pagination = true)
    {
        $query = $this->whereIn('event_id', $object)->latest('created_at');

        if ($pagination) {
            if (\Agent::isMobile()) {
                $orders = $query->simplePaginate();
            } else {
                $orders = $query->paginate();
            }
        } else {
            $orders = $query->get();
        }

        return $orders;
    }
}

resources/views/admin/pages/edit.blade.php
@extends('layouts.app')

@section('content')
    @php
        /** @var \Form */
    @endphp
    <div class="container">
        @include('layouts.errors')
        <div class="row justify-content-center">
            <div class="col-md-8 mb-1">
                {{ Form::model($page, ['route' => ['admin.pages.update', $page->id], 'files' => true]) }}
                <div class="card">
                    @method('PATCH')
                    <div class="card-header">
                        <div class="form-group">
                        {{ Form::label('title', __('messages.title')) }}
                        {{ Form::text('title', $page->title, ['class' => 'form-control']) }}
                        </div>
                        <div class="form-group">
                            {{ Form::label('alias', __('messages.alias')) }}
                            {{ Form::text('alias', $page->alias, ['class' => 'form-control', 'disabled' => true]) }}
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            {{ Form::label('description', __('messages.desc')) }}
                            {{ Form::text('description', $page->description, ['class' => 'form-control']) }}
                        </div>
                        <div class="form-group">
                        {{ Form::label('body', __('messages.body')) }}
                        {{ Form::textarea('body', $page->body, ['class' => 'form-control', 'rows' => 4]) }}
                        </div>
                        @if ($page->file && $page->file->is_image)
                        <a href="/uploads/{{ $page->file->hash }}" data-fancybox data-caption="{{ $page->file->filename }}">
                            <img class="bd-placeholder-img card-img-top"
                                 src="/uploads/{{ $page->file->hash }}"
                                 alt="{{ $page->file->filename }}"
                                 style="width: 100px">
                        </a>
                        @endif
                        <div class="form-group">
                            {{ Form::label('image', __('messages.other_file')) }}
                            {{ Form::file('image', ['class' => 'form-control-file']) }}
                        </div>
                    </div>
                    <div class="card-footer text-muted">
                        {{ __('messages.created') }}{{ $page->created_at }}
                        @if ($page->updated_at > $page->created_at)
                            <span class="float-right">
                            {{ __('messages.updated') }}{{ $page->updated_at }}
                        </span>
                        @endif
                    </div>
                </div>
                <div class="text-center mt-2">
                    {{ Form::submit(__('messages.save'), ['class' => 'btn btn-primary']) }}
                    <a class="btn btn-secondary" href="{{ route('admin.pages.index') }}" role="button">
                        {{ __('messages.cancel') }}
                    </a>
                </div>
                {{ Form::close() }}
            </div>
        </div>
    </div>
@endsection

resources/views/admin/pages/index.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="container">
        <h1>{{ __('messages.pages') }}</h1>
        @if (!empty($pages))
        <div class="table-responsive">
            <table class="table table-striped table-sm">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>{{ __('messages.title') }}</th>
                        <th>{{ __('messages.alias') }}</th>
                        <th>{{ __('messages.create_date') }}</th>
                        <th class="text-center">{{ __('messages.actions') }}</th>
                    </tr>
                </thead>
                <tbody>
                @foreach ($pages as $item)
                    <tr>
                        <td>{{ $item->id }}</td>
                        <td>{{ $item->title }}</td>
                        <td>{{ $item->alias }}</td>
                        <td>{{ $item->created_at }}</td>
                        <td class="text-center">
                            <a href="{{ route('admin.pages.edit', ['id' => $item->id]) }}" title="{{ __('messages.edit') }}">
                                <span data-feather="edit"></span>
                            </a>
                            <a href="{{ url($item->alias) }}" title="{{ __('messages.view') }}" target="_blank">
                                <span data-feather="eye"></span>
                            </a>
                        </td>
                    </tr>
                @endforeach
        @endif
    </div>
@endsection