routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');
Route::resource('event', 'EventController')->only('show');
Route::resource('order', 'OrderController')->only('store');

Auth::routes();

Route::group(['namespace' => 'Admin', 'middleware' => 'auth'], function () {
    Route::get('admin', 'DashboardController@index')->name('admin');
    Route::resource('admin/pages', 'PageController')->only('index', 'edit', 'update')->names('admin.pages');
    Route::get('admin/orders', 'OrderController@index')->name('admin.orders');
    Route::get('admin/orders/{id}/delete', 'OrderController@destroy')->name('admin.orders.delete');
    Route::get('admin/events', 'EventController@index')->name('admin.events');
    Route::get('admin/users', 'UserController@index')->name('admin.users');
    Route::get('admin/roles', 'RoleController@index')->name('admin.roles');
});

resources/views/layouts/app.blade.php
@include('layouts.header')
<body>
    <div id="app">
        @include('layouts.nav')

        <main class="py-4">
            @yield('content')
        </main>

        @include('layouts.footer')
    </div>
</body>
</html>

resources/views/layouts/errors.blade.php
@if ($errors->any())
    <div class="row justify-content-center">
        <div class="col-md-6 mb-1">
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        </div>
    </div>
@endif

resources/views/layouts/footer.blade.php
    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="{{ asset('js/jquery.fancybox.min.js') }}" defer></script>
    <script src="//cdn.jsdelivr.net/npm/jquery@3/dist/jquery.min.js"></script>
    <script src="//stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

    @if (Request::is('event/*'))
    <script src="//unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
        feather.replace();
        jQuery(document).ready(function($) {
            $('form#order_form').on('submit', (function(e) {
                $.ajax({
                    type: $(this).attr('method'),
                    url: $(this).attr('action'),
                    data: $(this).serialize(),
                    success: function() {
                        jQuery('#order_form')[0].reset();
                        jQuery('#results').html('<div class="alert alert-success fade show" role="alert">{{ __('messages.success_msg') }}</div>');
                    },
                    error: function() {
                        jQuery('#results').html('<div class="alert alert-danger fade show" role="alert">{{ __('messages.error_msg') }}</div>');
                    }
                });
                e.preventDefault();
            }));
        });
    </script>
    @endif

    <!-- {{ $copyright }} -->

resources/views/layouts/header.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
@if (isset($meta['desc']))
    <meta name="description" content="{{$meta['desc']}}">
@endif
    <title>{{ config('app.name', 'Laravel') }}@if (isset($meta['title'])) - {{$meta['title']}}@endif</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/jquery.fancybox.min.css') }}" rel="stylesheet">
</head>

resources/views/layouts/nav.blade.php
    <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('messages.toggle_navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">
                    @if (!empty($events))
                        @foreach ($events as $event)
                            <li class="nav-item">
                                <a class="nav-link{{ Request::is('event/' . $event->id) ? ' active' : '' }}" href="{{ route('event.show', ['id' => $event->id]) }}">{{ $event->title }}</a>
                            </li>
                        @endforeach
                    @endif
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @endif
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('messages.logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                        @if (Auth::user()->role_id !== 2)
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('admin') }}" role="button">
                                    {{ __('messages.admin') }}
                                </a>
                            </li>
                        @endif
                    @endguest
                </ul>
            </div>
        </div>
    </nav>